/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    helloWorld
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Main_helloWorld
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
